'use strict';

const { Tournament } = require('./tournament');

/*
 * Pure (de)serialization of Room/Match/Tournament state for restart survival.
 * Mirrors the state fields of those classes — when adding a field there that a
 * rejoining player would need, extend these functions. Never persisted: ws,
 * ports/hook closures, timers, and the voice roster (clients re-join voice).
 */

function serializeMatch(m) {
  // Persist `shown` with in-flight swaps reverted (the same normalization
  // pause() applies) — swap revert timers don't survive a restart.
  const shown = [...m.shown];
  for (const { a, b } of [...m.pendingSwaps].reverse()) {
    [shown[a], shown[b]] = [shown[b], shown[a]];
  }
  return {
    names: m.names,
    difficultyKey: m.difficultyKey,
    boardSetting: m.boardSetting,
    firstTo: m.firstTo,
    totalRounds: m.totalRounds,
    round: m.round,
    wins: m.wins,
    history: m.history,
    phase: m.phase,
    firstCaller: m.firstCaller,
    boardKey: m.boardKey,
    boardOffset: m.boardOffset, // keeps the rotation cycle steady across a restart
    gridValues: m.gridValues,
    shown,
    target: m.target,
    fuse: m.fuse,
    charges: m.charges,
    puzzleSeq: m.puzzleSeq,
    lastSabAt: m.lastSabAt, // survive-restart cooldowns can't be reset by a redeploy
  };
}

// Overwrites state on a freshly constructed match (ports/hooks/timers intact)
// and leaves it paused; resume() re-arms the phase's timers once players return.
function reviveMatchInto(match, json) {
  Object.assign(match, json);
  match.pendingSwaps = [];
  match.puzzle = null; // regenerated by newPuzzle() on resume, like pause/resume
  match.paused = true;
  return match;
}

function serializeRoom(room) {
  const out = {
    code: room.code,
    settings: room.settings,
    phase: room.phase,
    boardCycle: room.boardCycle || 0,
    log: room.log,
    lastMatchEnd: room.lastMatchEnd || null,
    players: room.players.map(p => ({
      id: p.id,
      name: p.name,
      tag: p.tag,
      ready: !!p.ready,
      wantsRematch: !!p.wantsRematch,
      points: p.points,
      played: p.played,
      active: p.active !== false,
      graceUntil: p.connected ? null : (p.graceUntil || null),
    })),
  };
  if (room.match && room.match.phase !== 'done') out.match = serializeMatch(room.match);
  if (room.tournament && (room.phase === 'playing' || room.phase === 'tEnd')) {
    const t = room.tournament;
    out.tournament = {
      stage: t.stage,
      schedule: t.schedule,
      pendingPairs: t.pendingPairs || null,
      stageMatches: t.stageMatches.map(({ match, pair }) => ({ pair, match: serializeMatch(match) })),
    };
  }
  return out;
}

// makeRoom(code) is the transport's factory: it constructs the Room, wires its
// hooks, and registers it in the room map.
function reviveRoom(json, makeRoom) {
  const room = makeRoom(json.code);
  room.settings = json.settings;
  room.phase = json.phase;
  room.boardCycle = json.boardCycle || 0;
  room.log = json.log || [];
  room.lastMatchEnd = json.lastMatchEnd || null;
  room.players = json.players.map(p => ({ ...p, active: p.active !== false, ws: null, connected: false }));
  if (json.match) {
    room.match = reviveMatchInto(room.makeVersusMatch(), json.match);
  }
  if (json.tournament) {
    const t = new Tournament(room);
    t.stage = json.tournament.stage;
    t.schedule = json.tournament.schedule;
    t.pendingPairs = json.tournament.pendingPairs || null;
    t.stageMatches = json.tournament.stageMatches.map(({ pair, match }) => ({
      pair,
      match: reviveMatchInto(t.createMatch(pair[0], pair[1]), match),
      seatIn: s => (s === pair[0] ? 0 : 1),
    }));
    room.tournament = t;
    room.needsKick = true; // first returner nudges the schedule (reconnect.js)
  }
  return room;
}

module.exports = { serializeMatch, reviveMatchInto, serializeRoom, reviveRoom };
